name: endec_nbt
description: An implementation of Minecraft's Named Binary Tag format for endec
version: 0.1.4
repository: https://github.com/gliscowo/endec.dart

resolution: workspace
publish_to: https://pub.wispforest.io

environment:
  sdk: ^3.6.0

dependencies:
  endec:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.1.1
