name: endec_builder
description: A build system builder for automatically generating struct endecs
version: 0.1.0
repository: https://github.com/gliscowo/endec.dart

resolution: workspace
publish_to: https://pub.wispforest.io

environment:
  sdk: ^3.6.0

dependencies:
  endec:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  analyzer: ^7.2.0
  build: ^2.4.1
  meta: ^1.15.0
  source_gen: ^2.0.0
  source_helper: ^1.3.4

dev_dependencies:
  lints: ^5.1.1
